/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leehour_jnidemo2_JNI */

#ifndef _Included_com_leehour_jnidemo2_JNI
#define _Included_com_leehour_jnidemo2_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leehour_jnidemo2_JNI
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leehour_jnidemo2_JNI_encode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_leehour_jnidemo2_JNI
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leehour_jnidemo2_JNI_decode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
